'use client'

/**
 * HeroVideo — gère l'état chargement/erreur de la vidéo hero.
 *
 * Comportement :
 *  - Pendant le chargement ou si le fichier est absent → placeholder animé visible
 *  - Dès que la vidéo commence à jouer (onCanPlay) → placeholder masqué, vidéo visible
 *  - Si erreur → placeholder reste visible indéfiniment
 *
 * Pour activer la vraie vidéo : déposer /demo/clyro-hero-demo.mp4
 * (720p H.264 baseline, < 4 MB) dans apps/web/public/demo/
 */

import { useState, useRef } from 'react'
import { cn } from '@/lib/utils'
import { Badge } from '@/components/ui/badge'
import { SpinnerAI } from '@/components/ui/spinner'
import { Maximize2, Play } from 'lucide-react'

export function HeroVideo() {
  const [loaded,  setLoaded]  = useState(false)
  const [errored, setErrored] = useState(false)
  const videoRef = useRef<HTMLVideoElement>(null)

  const showPlaceholder = !loaded || errored

  return (
    <div className="relative rounded-2xl overflow-hidden shadow-2xl border border-border/30 aspect-video bg-black">

      {/* ── Vidéo réelle ─────────────────────────────────────────────────────── */}
      <video
        ref={videoRef}
        autoPlay
        loop
        muted           // obligatoire pour autoplay cross-browser
        playsInline
        preload="metadata"
        poster="/demo/hero-poster.jpg"
        onCanPlay={() => setLoaded(true)}
        onError={() => setErrored(true)}
        aria-label="CLYRO demo — faceless video generation workflow"
        className={cn(
          'absolute inset-0 w-full h-full object-cover transition-opacity duration-700',
          loaded && !errored ? 'opacity-100' : 'opacity-0 pointer-events-none',
        )}
      >
        <source src="/demo/clyro-hero-demo.mp4" type="video/mp4" />
      </video>

      {/* ── Placeholder CSS (visible pendant le chargement ou si fichier absent) */}
      <div
        aria-hidden="true"
        className={cn(
          'absolute inset-0 bg-gradient-to-br from-blue-900/60 via-violet-900/50 to-indigo-900/60',
          'flex flex-col items-center justify-center gap-4',
          'transition-opacity duration-700',
          showPlaceholder ? 'opacity-100' : 'opacity-0 pointer-events-none',
        )}
      >
        {/* Interface de génération simulée */}
        <div className="w-4/5 max-w-xs space-y-3">
          <div className="flex items-center gap-2">
            <SpinnerAI size="sm" />
            <span className="font-body text-sm text-white/80">Generating scenes...</span>
            <span className="font-mono text-xs text-white/50 ml-auto">Scene 4 / 6</span>
          </div>
          <div className="h-1 bg-white/10 rounded-full overflow-hidden">
            <div className="h-full w-2/3 bg-gradient-to-r from-blue-400 to-violet-400 rounded-full" />
          </div>
          <div className="grid grid-cols-3 gap-2 mt-3">
            {[
              { label: 'Scene 1', done: true  },
              { label: 'Scene 2', done: true  },
              { label: 'Scene 3', active: true },
            ].map((s) => (
              <div
                key={s.label}
                className="aspect-video bg-white/5 rounded-lg border border-white/10 flex items-center justify-center relative overflow-hidden"
              >
                {s.done && <Play size={12} className="text-white/40" />}
                {s.active && (
                  <div className="absolute inset-0 bg-blue-500/10 border border-blue-400/30 rounded-lg flex items-center justify-center">
                    <SpinnerAI size="sm" />
                  </div>
                )}
                <Badge
                  variant={s.done ? 'success' : 'info'}
                  className="absolute top-1 right-1 text-[9px] px-1 py-0"
                  dot={!!s.active}
                >
                  {s.done ? 'HD' : 'AI'}
                </Badge>
                <span className="absolute bottom-1 left-1 font-mono text-[9px] text-white/40">{s.label}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ── Overlays communs (visibles dans les deux cas) ────────────────────── */}
      {/* Gradient bas pour lisibilité des badges */}
      <div className="absolute inset-x-0 bottom-0 h-16 bg-gradient-to-t from-black/60 to-transparent pointer-events-none" />

      {/* Badge "Generated by CLYRO" */}
      <div className="absolute bottom-3 left-3 z-10">
        <Badge variant="success" className="backdrop-blur-sm bg-success/20 text-white border-success/30">
          Generated by CLYRO in 4 min
        </Badge>
      </div>

      {/* Icône fullscreen décorative */}
      <div className="absolute bottom-3 right-3 z-10 bg-black/50 backdrop-blur-sm rounded-lg p-2 border border-white/10">
        <Maximize2 size={13} className="text-white/60" />
      </div>
    </div>
  )
}
